github_repo: 'ourfor/diary_hexo'
# For use with the "Edit on GitHub" button, this represents the path to the
# source markdown, from the root of the GitHub repository, with no leading
# slash.  It's set to 'source' here as that's the Hexo default, though it can
# vary based on repository configuration (some variations use the
# less-preferred `content` directory.
content_root: 'source'

css_bundle: meteor
nav_class: dark

favicon: /images/ourfor.jpg

logo:
  nav_mobile: /images/zip.jpg
  url: https://diary.ourfor.top
  title: 'ä¸€ä¸ªç–¯å­çš„ç”Ÿæ´»å°è®°'
  subtitle: 'Diary'


apis:
  baidu:  
  ga: UA-61934506-3       
  marketo: 999-999-9999
  segment: abcabcabcabc
  docsearch:
    apiKey: 
    indexName: 

# nav:
#   'language':
#     url: http://www.meteor.com/tutorials
#     partial: illustration-guide
#     target: _new
#     active: false
#   'Guide':
#     url: http://guide.meteor.com
#     partial: illustration-compass
#     active: false
#   'API Docs':
#     url: http://docs.meteor.com
#     partial: illustration-logs
#     active: false

ad:
  enable: false

sidebar:
  null:
    - index
    - ç¾æ–‡
    - é˜…è¯»
  Config:
    - hexo-github-codingæ­å»ºä¸ªäººåšå®¢
    - å¤ªææ‹³å¥½éš¾
    - å°è¯´è¿˜æ˜¯å¾—å¤šçœ‹
    - æš‘å‡è§„åˆ’
  Other:
    - è¯»ã€Šçº¢æ¥¼æ¢¦ã€‹æœ‰æ„Ÿ
    - åˆå°Typecho


valine:
  enable: true
  appId: LQcg6cueG8cMcLf9gSrAhF6d-gzGzoHsz
  appKey: zAMFPgKrAh09qqQDGHvdU0Uq
  notify: true
  placeholder: ç­‰ä¸€ä¸ªäººï¼Œè¿˜æ˜¯ç­‰ä¸€ä¸ªæ•…äº‹ï¼Ÿ\nğŸ‡ğŸˆğŸ‰ğŸŠğŸ‹ğŸŒğŸğŸğŸğŸğŸ‘ğŸ’ğŸ“ğŸ¥ğŸ…
  avatar: robohash
  


social_links:
  github: 'https://github.com/ourfor'
  twitter: 
